### ISSUE TITLE
WebComponent made with quarkus not accessible

### ISSUE THREAD

**Issue by khauser** [vaadin/quarkus#191]
Hi,

I have small project to test the a micro-fontend architecture using webcomponents. First I created it with Spring Boot and now I wanted to switch over to Quarkus. The solution with spring was working well. But the one with Quarkus fail already in the WebComponent creation and direct access process. Calling http://localhost:8080/vaadin-app/some-mediawidget.js where I get a "No views found"-page. Normally I should see javascript code I guess.

Did somebody already tried to create a webcomponent with quarkus? Or do have some hints here?

My test is using a small nodejs project with this server file:
```
import express from "express";
import { createProxyMiddleware } from 'http-proxy-middleware';
import path from "path";

const app = express();
const port = 3000;

app.use('/vaadin-app', createProxyMiddleware({
  target: 'http://localhost:8080/vaadin-app',
  changeOrigin: true,
  logLevel: 'debug',
}));


app.use(express.static("public"));

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
```
So all request to http://localhost:3000/vaadin-app will be routed to a WebComponent http://localhost:8080/vaadin-app.

Some more files:

SomeMediawidget.java
```java
public class SomeMediawidget extends VerticalLayout
{
    private static final long serialVersionUID = 3203183198469758631L;

    private AzureBlobService azureBlobService;
    private FileEntryTreeGrid treeGrid;
    private Map<String, FileEntry> fileEntries;
    private VerticalLayout detailLayout;

    @Inject
    public SomeMediawidget(AzureBlobService azureBlobService)
    {
        this.azureBlobService = azureBlobService;
        setSizeFull();
        setSpacing(false);
        setPadding(false);

        initStructure();
    }
...
```

SomeMediawidgetExporter.java
```java
public class SomeMediawidgetExporter extends WebComponentExporter<SomeMediawidget>
{
    public SomeMediawidgetExporter()
    {
        super("some-mediawidget");
    }

    @Override
    protected void configureInstance(WebComponent<SomeMediawidget> webComponent,
                    SomeMediawidget someMediawidget)
    {
        // Not used
    }
}
```

application.yml
```yml
quarkus:
  http:
    port: 8080
    root-path: /vaadin-app
    cors:
      ~: true
      origins: http://localhost:3000
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST, PUT, DELETE
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
      access-control-allow-credentials: true

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.some
```
build.gradle
```gradle
plugins {
    // spring boot plugin
    id 'io.quarkus'

    // Vaadin support
    id 'com.vaadin' version '24.6.5'
}
...
dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-rest-jackson'
    implementation 'io.quarkus:quarkus-rest'
    implementation 'io.quarkus:quarkus-undertow'
    implementation 'io.quarkus:quarkus-config-yaml'

    // Vaadin
    implementation enforcedPlatform("com.vaadin:vaadin-bom:$vaadinVersion")
    implementation group: 'com.vaadin', name: 'vaadin-quarkus-extension', version: "${vaadinVersion}"
    implementation group: 'com.vaadin', name: 'vaadin-lumo-theme', version: "${vaadinVersion}"
```

Vaadin: 24.6.5
Quarkus: 3.18.3
Java: Oracle GraalVM 21.0.2+13.1
Gradle: 8.7

Best,
Karsten
